config/routes.rb
Rails.application.routes.draw do
  resources :flats
  devise_for :users
  root to: "pages#home"
  resources :houses
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :house
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :house
end

app/models/flat.rb
class Flat < ApplicationRecord
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/models/house.rb
class House < ApplicationRecord
  belongs_to :user
  has_many :comments
  has_many :favorites
  has_one :service
  has_many_attached :photos

  validates :suptotal, comparison: { greater_than_or_equal_to: :supcubierta }
  validates :provincia, :domicilio, :tipo, :condicion, :precio,
            :descripcion, :dormitorio, :domicilio, :bano, :supcubierta, :suptotal,
            :cochera, :photos, presence: true

  include PgSearch::Model
  pg_search_scope :search_houses, against: %i[provincia departamento localidad
                                              barrio domicilio tipo precio condicion
                                              address],
                                  using: { tsearch: { prefix: true } }

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/models/service.rb
class Service < ApplicationRecord
  belongs_to :house
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :comments
  has_many :favorites
  has_many :houses
  has_one_attached :photo
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  before_action :set_flat, only: %i[ show edit update destroy ]

  # GET /flats or /flats.json
  def index
    @flats = Flat.geocoded
    @markers = @flats.geocoded.map do |flat|
      {
        lat: flat.latitude,
        lng: flat.longitude,
        info_window_html: render_to_string(partial: "info_window", locals: { flat: flat }),
        marker_html: render_to_string(partial: "marker")
      }
    end
  end


  # GET /flats/1 or /flats/1.json
  def show
  end

  # GET /flats/new
  def new
    @flat = Flat.new
  end

  # GET /flats/1/edit
  def edit
  end

  # POST /flats or /flats.json
  def create
    @flat = Flat.new(flat_params)

    respond_to do |format|
      if @flat.save
        format.html { redirect_to flat_url(@flat), notice: "Flat was successfully created." }
        format.json { render :show, status: :created, location: @flat }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @flat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /flats/1 or /flats/1.json
  def update
    respond_to do |format|
      if @flat.update(flat_params)
        format.html { redirect_to flat_url(@flat), notice: "Flat was successfully updated." }
        format.json { render :show, status: :ok, location: @flat }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @flat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /flats/1 or /flats/1.json
  def destroy
    @flat.destroy

    respond_to do |format|
      format.html { redirect_to flats_url, notice: "Flat was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_flat
      @flat = Flat.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def flat_params
      params.require(:flat).permit(:name, :address)
    end
end

app/controllers/houses_controller.rb
class HousesController < ApplicationController
  # before_action :set_user, only: %i[new create edit update destroy]
  skip_before_action :authenticate_user!, only: %i[index show]
  before_action :set_house, only: %i[show edit update destroy]

  def index
    if params[:query].present?
      @houses = House.search_houses(params[:query])
    else
      @houses = House.all
    end

    @houses = House.all
    # The `geocoded` scope filters only flats with coordinates
    @markers = @houses.geocoded.map do |house|
      {
        lat: house.latitude,
        lng: house.longitude,
        info_window_html: render_to_string(partial: "info_window", locals: { house: house }),
        marker_html: render_to_string(partial: "marker")
      }
    end
  end

  def show
    @marker = {
      lat: @house.latitude,
      lng: @house.longitude,
      info_window_html: render_to_string(partial: "info_window", locals: { house: @house }),
      marker_html: render_to_string(partial: "marker")
    }
  end

  def new
    @house = House.new
  end

  def create
    @house = House.new(house_params)
    @house.user_id = current_user.id
    if @house.save
      redirect_to house_path(@house)
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    @house.update(house_params)
    redirect_to house_path(@house)
  end

  def destroy
    @house.destroy
    redirect_to houses_path, status: :see_other
  end

  private

  def house_params
    params.require(:house).permit(:provincia, :departamento, :localidad,
                                  :barrio, :domicilio, :tipo, :condicion, :precio,
                                  :descripcion, :foto, :cochera, :dormitorio, :bano, :supcubierta, :suptotal, :mascota,
                                  :user_id, :expensa, :address, photos: [])
  end

  def set_house
    @house = House.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
    if params[:query].present?
      @houses = House.search_houses(params[:query])
    else
      @houses = House.all
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/flats/_flat.html.erb
<div id="<%= dom_id flat %>">
  <p>
    <strong>Name:</strong>
    <%= flat.name %>
  </p>

  <p>
    <strong>Address:</strong>
    <%= flat.address %>
  </p>

</div>

app/views/flats/_form.html.erb
<%= simple_form_for(@flat) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :address,
    input_html: {data: {address_autocomplete_target: "address"}},
    wrapper_html: {data: {controller: "address-autocomplete", address_autocomplete_api_key_value: ENV["MAPBOX_API_KEY"]}}
  %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>

<% end %>

app/views/flats/_info_window.html.erb
<h2><%= flat.name %></h2>
<p><%= flat.address %></p>

app/views/flats/edit.html.erb
<h1>Editing flat</h1>

<%= render "form", flat: @flat %>

<br>

<div>
  <%= link_to "Show this flat", @flat %> |
  <%= link_to "Back to flats", flats_path %>
</div>

app/views/flats/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Flats</h1>

<div id="flats">
  <% @flats.each do |flat| %>
    <%= render flat %>
    <p>
      <%= link_to "Show this flat", flat %>
    </p>
  <% end %>
</div>

<%= link_to "New flat", new_flat_path %>

<div style="width: 100%; height: 600px;"
  data-controller="map"
  data-map-markers-value="<%= @markers.to_json %>"
  data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"></div>

app/views/flats/new.html.erb
<h1>New flat</h1>

<%= render "form", flat: @flat %>

<br>

<div>
  <%= link_to "Back to flats", flats_path %>
</div>

app/views/flats/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @flat %>

<div>
  <%= link_to "Edit this flat", edit_flat_path(@flat) %> |
  <%= link_to "Back to flats", flats_path %>

  <%= button_to "Destroy this flat", @flat, method: :delete %>
</div>

app/views/houses/_form.html.erb
<%# <div class="container">
  <div class="row justify-content-center">
    <div class="col-md-8"> %>


<div class="container">
<hr>
  <div class="m-3" onchange="autocomplete();" onkeyup='autocomplete()'>
    <%= simple_form_for(house) do |f| %>
      <div class="row">
        <div class="col-md-6 d-flex flex-column">
          <%= f.input :condicion, collection: ['Venta', 'Alquiler', 'Alquiler Temporario', 'Permuta'] %>
          <%= f.input :domicilio %>
          <%= f.input :provincia, collection: ['Buenos Aires', 'Ciudad Autónoma de Buenos Aires', 'Catamarca','Chaco', 'Chubut', 'Córdoba', 'Corrientes','Entre Ríos','Formosa', 'Jujuy', 'La Pampa', 'La Rioja','Mendoza', 'Misiones', 'Neuquén', 'Río Negro', 'Salta', 'San Juan', 'San Luis', 'Santa Cruz', 'Santa Fé', 'Santiago del Estero', 'Tierra del Fuego', 'Tucumán'], prompt: 'Seleccionar provincia', input_html: {id: 'provincia-select'} %>
          <div id="mendoza-departamentos" style="">
            <%= f.input :departamento, collection: ['Capital', 'Godoy Cruz', 'Guaymallén', 'Junín', 'La Paz', 'Las Heras', 'Lavalle', 'Luján de Cuyo', 'Maipú', 'Malargüe', 'Rivadavia', 'San Carlos', 'San Martín', 'San Rafael', 'Santa Rosa', 'Tunuyán', 'Tupungato', '25 de Mayo'], prompt: 'Seleccionar departamento' %>
          </div>
          <%# <div id="otro-departamento" style=""> %>
            <%#= f.input :departamento, placeholder: 'Ingresar departamento (o partido)' %>
          <%# </div> %>
          <%= f.input :localidad %>
          <%= f.input :barrio %>
          <%= f.input :tipo, collection: ['Casa', 'Departamento', 'Cabaña', 'Cochera', 'Duplex', 'Loft', 'Bodega', 'Bodega con Viñedo', 'Campo', 'Chalet', 'Condominio', 'Edificio', 'Estacion de Servicio', 'Fábrica', 'Finca', 'Fondo de Comercio', 'Fraccionamiento', 'Galpón', 'Hotel', 'Industria', 'Local Comercial', 'Lote', 'Loteo', 'Negocio', 'Oficina', 'PH', 'Piso', 'Playa de Estacionamiento', 'Quinta', 'Semipiso', 'Triplex', 'Viñedo'] %>
        </div>
        <div class="col-md-6 d-flex flex-column">
          <%= f.input :descripcion, label: "Descripción" %>
          <div class="row">
            <div class="col-6">
              <%= f.input :bano, label: "Baños" %>
            </div>
            <div class="col-6">
              <%= f.input :dormitorio, label: "Dormitorios"  %>
            </div>
          </div>
          <div class="row">
            <div class="col-6">
              <%= f.input :supcubierta, label: "Superficie Cubierta m²" %>
            </div>
            <div class="col-6">
              <%= f.input :suptotal, label: "Superficie Total m²" %>
            </div>
          </div>
          <div class="row">
            <div class="col-6">
              <%= f.input :cochera, collection: ['Sí', 'No'] %>
            </div>
            <div class="col-6">
              <div style="display: inline-block;">
                <%= f.input :mascota, label: "¿Permite Mascota?"  %>
                <%= f.input :expensa, label: "¿Tiene Expensas?" %>
              </div>
            </div>
          </div>
          <%= f.input :precio %>
          <%= f.input :photos, as: :file, input_html: {multiple: true}, label: "Cargar Fotos"  %>
          <%= f.input :address, input_html:{class: "d-none"}, label:false %>
          <%= f.submit 'ACEPTAR', class: 'btn  w-100', style: 'background-color: #951920; color: #fff;' %>
        </div>
      </div>
    <% end %>
  </div>
  <hr>


</div>
<script>
function autocomplete() {

  let calleNum = document.getElementById('house_domicilio').value
  let departamento = document.getElementById('house_departamento').value
  let provincia = document.getElementById('provincia-select').value
  let dominterpolado = `${calleNum}, ${departamento}, ${provincia}`
  console.log(dominterpolado)
  let address = document.getElementById('house_address')
  address.value = dominterpolado

  // console.log("calle", calleNum)
  // console.log("depto", departamento)
  // console.log("prov", provincia)


}
</script>
<%#
<script>
  document.addEventListener("DOMContentLoaded", function(event) {
    var provinciaSelect = document.getElementById("provincia-select");
    var mendozaDepartamentos = document.getElementById("mendoza-departamentos");
    var otroDepartamento = document.getElementById("otro-departamento");

    provinciaSelect.addEventListener("change", function(event) {
      if (provinciaSelect.value == "Mendoza") {
        mendozaDepartamentos.style.display = "block";
        otroDepartamento.style.display = "none";
      } else {
        mendozaDepartamentos.style.display = "none";
        otroDepartamento.style.display = "block";
      }
    });
  });
</script> %>

app/views/houses/_info_window.html.erb
<a href="<%= house_path(house.id) %>" style="all: unset;">
  <div>
    <div class="badge rounded-pill bg-primary fs-6">
      <%= house.condicion %>
    </div>
    <div style="border: 2px solid #951920; padding: 12px; margin-top: 5px">
      <p><%= house.address %></p>
      <div class="d-flex justify-content-between align-items-center">
        <i class="fa-solid fa-bed"></i> <%= house.dormitorio %>
        <i class="fa-solid fa-bath"></i> <%= house.bano %>
        <% if  house.cochera == "sí" %>
          <i class="fa-solid fa-car"> </i>
        <% end %>
        <div class="">
          <%= image_tag('https://res.cloudinary.com/dmizpueuw/image/upload/v1679941758/FARRAN%20PROPIEDADES/farran_propiedades_icon_sup_total.svg', style:"width: 1.25rem; height: 1.25rem") %>
          <%=house.suptotal%>
        </div>
        <div class="">
          <%= image_tag('https://res.cloudinary.com/dmizpueuw/image/upload/v1678914771/FARRAN%20PROPIEDADES/farran_propiedades_icon_sup_cub_v2_uekziy.svg', style:"width: 1.25rem; height: 1.25rem") %>
          <%=house.supcubierta %>
        </div>
      </div>
    </div>
  </div>
</a>

app/views/houses/_marker.html.erb
<%= image_tag("https://res.cloudinary.com/dmizpueuw/image/upload/v1680065541/FARRAN%20PROPIEDADES/FARRAN_PROPIEDADES_logo_sin_texto_radf1i.jpg", height: 30, width: 30, alt: "Logo", style:"border: 1px solid #951920") %>

app/views/houses/edit.html.erb
<h1>EDITAR UNA PROPIEDAD</h1>

<%= render "form", house: @house %>

app/views/houses/index.html.erb
<div class="container">

  <h1>Todos las Propiedades</h1>
  <%= link_to "Crear Nueva Propiedad", new_house_path, class:"m-5" %>

  <div class="m-5">
    <%= form_with url: houses_path, method: :get, class: "d-flex" do %>
      <%= text_field_tag :query,
        params[:query],
        class: "form-control",
        placeholder: "Buscá tu próxima propiedad"
      %>
      <%= submit_tag "Buscar", class: "btn btn-primary ms-1", style:"background-color: #951920; border-color: #951920;" %>
    <% end %>
  </div>

  <div class="m-5">
    <div class="row">
      <% @houses.each do |house| %>
        <div class="col-lg-3 col-md-6 col-sm-12 mb-4">
          <div class="card h-100 p-1" >
            <div id="carouselExampleControls<%= house.id %>" class="carousel slide" data-interval="false">
              <div class="carousel-inner">
                <a href="<%= house_path(house.id) %>">
                  <% house.photos.each_with_index do |photo, index| %>
                    <div class="carousel-item <%= index == 0 ? 'active' : '' %>">
                      <%= cl_image_tag photo.key, height: 250, crop: :fill, gravity: :center, class: "d-block w-100% mx-auto" %>
                    </div>
                  <% end %>
                </a>
              </div>
            </div>
            <div class="card-body">
              <h5 class="card-title"><%= house.domicilio %></h5>
              <p class="card-text"><%= house.departamento %> - <%= house.provincia %></p>
            </div>
            <div class="card-footer">
              <div class="row">
                <div class="col">
                  <%= image_tag('https://res.cloudinary.com/dmizpueuw/image/upload/v1679941758/FARRAN%20PROPIEDADES/farran_propiedades_icon_sup_total.svg', style:"width: 30px; height: 30px") %>
                  <%=house.suptotal%>
                </div>
                <div class="col">
                  <%= image_tag('https://res.cloudinary.com/dmizpueuw/image/upload/v1678914771/FARRAN%20PROPIEDADES/farran_propiedades_icon_sup_cub_v2_uekziy.svg', style:"width: 30px; height: 30px") %>
                  <%=house.supcubierta %>
                </div>
              </div>
              <hr>
              <div class="row">
                <div class="col">
                  <i class="fa-solid fa-bed"></i> <%= house.dormitorio %>
                </div>
                <div class="col">
                  <i class="fa-solid fa-bath"></i> <%= house.bano %>
                </div>
                <div class="col">
                  <% if  house.cochera == "sí" %>
                    <i class="fa-solid fa-car"> </i>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>

  <div style="width: 100%; height: 400px;"
    data-controller="map"
    data-map-markers-value="<%= @markers.to_json %>"
    data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>

<br>
</div>

app/views/houses/new.html.erb
<h1>CREAR UNA PROPIEDAD NUEVA</h1>
<div>
  <%= form_with model: @house do |f| %>
    <%= f.label :provincia %>
    <%= f.text_field :provincia %>
    <%= f.label :departamento %>
    <%= f.text_field :departamento %>
    <%= f.label :localidad %>
    <%= f.text_field :localidad %>
    <%= f.label :barrio %>
    <%= f.text_field :barrio %>
    <br>
    <%= f.label :domicilio %>
    <%= f.text_field :domicilio %>
    <%= f.label :tipo %>
    <%= f.text_field :tipo %>
    <%= f.label :condicion %>
    <%= f.text_field :condicion %>
    <%= f.label :precio %>
    <%= f.text_field :precio %>
    <%= f.label :descripcion %>
    <%= f.text_field :descripcion %>
    <%= f.label :foto %>
    <%= f.text_field :foto %>
    <%= f.label :cochera %>
    <%= f.text_field :cochera %>
    <%= f.label :dormitorio %>
    <%= f.number_field :dormitorio %>
    <%= f.label :bano %>
    <%= f.number_field :bano %>
    <%= f.label :supcubierta %>
    <%= f.number_field :supcubierta%>
    <%= f.label :suptotal %>
    <%= f.number_field :suptotal %>
    <%= f.label :mascota %>
    <%= f.check_box :mascota%>
    <%= f.label :expensa %>
    <%= f.check_box :expensa%>
    <br>
    <%= f.submit %>
  <% end %>
</div>

app/views/houses/show.html.erb
<div class="pt-5">
  <div class="house_show">
    <div class="card-show">
      <div class="card__title">
        <div class="icon">
          <a href="<% houses_path %>"><i class="fa fa-arrow-left"></i></a>
          <%= @house.condicion %>
        </div>
        <%= image_tag "", style: "width: 50px; height: 50px; margin-left:50px;" %>
      </div>
      <div class="card__body">
        <div class="half">
          <div class="featured_text">
            <h1><%= @house.domicilio %></h1>
            <%= @house.provincia %> - <%= @house.departamento%> - <%= @house.localidad %> - <%= @house.barrio %>
            <p class="price">$ <%= @house.precio %></p>
          </div>




<div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel">
  <div class="carousel-inner">
    <% @house.photos.each_with_index do |photo, index| %>
      <div class="carousel-item <%= index == 0 ? 'active' : '' %>">
        <%= cl_image_tag photo.key, height: 400, crop: :fill, class:"d-block w-100" %>
      </div>
    <% end %>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>




        </div>
        <div class="half mt-5">
          <h5>DATOS DE LA PROPIEDAD</h5>
          <div class="description mt-5">
            <hr>
            <p>TIPO: <%= @house.tipo%></p>
            <hr>
            <p>SUPERFICIE TOTAL: <%= @house.suptotal%>m²    -    SUPERFICIE CUBIERTA: <%= @house.supcubierta%>m²</p>
            <hr>
            <p>BAÑOS: <%= @house.bano%></p>
            <hr>
            <p>DORMITORIOS: <%= @house.dormitorio%></p>
            <hr>
            <p>COCHERA: <%= @house.cochera%></p>
            <hr>
            <p>MASCOTA: <%= @house.mascota%> -  EXPENSAS: <%= @house.expensa%></p>
            <hr>
          </div>

          <div class="reviews d-flex">
            <p>BAÑOS:   </p>
            <ul class="stars">
              <%='<li><i class="fa-solid fa-heart"></i></li>'.html_safe *  @house.bano %><%='<li><i class="fa-regular fa-heart"></i></li>'.html_safe *  (5 - @house.bano) %>
            </ul>
          </div>
        </div>

      </div>
      <p class="mx-5">DESCRIPCIÓN: <%= @house.descripcion%></p>

      <div class="card__footer">
        <div class="recommend">
          <p><%= @house.provincia %></p>
          <h3>by <a href="<%= user_session_path%>"><%= @house.user.email %></a></h3>
          <%= link_to "Editar", edit_house_path %>
          <%= link_to "Eliminar",
            house_path(@house),
            data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}
          %>
        <br>
        <%= link_to "Volver a todas las propiedades", houses_path %>
        </div>
        <div class="action">
          <a href="<%= @house.departamento %>" class="btn btn-success text-uppercase" target="_blank"><i class="fa-brands fa-square-whatsapp"></i>  CONSULTAR </a>
        </div>
      </div>
    </div>
  </div>
  <div style="width: 100%; height: 400px;"
  data-controller="map"
  data-map-markers-value="<%= [@marker].to_json %>"
  data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>
</div>

<div class="container">

</div>

<%# link para Agregar más información %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FarranPropiedades</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.css" rel="stylesheet">
    <script src="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.js"></script>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Contrail+One&family=Merriweather&family=Montserrat&display=swap" rel="stylesheet">
  </head>

  <body style="padding-top: 65px;">
    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>

    <%= yield %>
  </body>
</html>

app/views/pages/_formbuscador.html.erb
<%# EL BUSCADOR YA RECOPILA LA INFORMACION DE LOS TRES TAGS, Y LOS GUARDA EN UNO OCULTO PARA HACER LA BUSQUEDA, PERO A LA HORA DE BUSCAR, LA BUSQEUDA LA HACE EN BLANCO, SIN NINGUN FILTRO. HAY ALGUITO FINAL QUE NO ESTOY PUDIENDO HACER TODAVIA. %>

<div class="m-5 mb-0 p-3 border border-white" onchange="searchcomplete();" onkeyup="searchcomplete()">
  <%= form_with url: houses_path, method: :get, class: "d-flex", id: "my-form" do %>
    <%= select_tag :condicion,
      options_for_select(['Venta', 'Alquiler', 'Alquiler Temporario', 'Permuta'], params[:condicion]),
      class: "form-check ms-1",
      data: {action: "change->search-variables#updateQuery"}
    %>
    <%= select_tag :tipo,
      options_for_select(['Casa', 'Departamento', 'Cabaña', 'Cochera', 'Duplex', 'Loft', 'Bodega', 'Bodega con Viñedo', 'Campo', 'Chalet', 'Condominio', 'Edificio', 'Estacion de Servicio', 'Fábrica', 'Finca', 'Fondo de Comercio', 'Fraccionamiento', 'Galpón', 'Hotel', 'Industria', 'Local Comercial', 'Lote', 'Loteo', 'Negocio', 'Oficina', 'PH', 'Piso', 'Playa de Estacionamiento', 'Quinta', 'Semipiso', 'Triplex', 'Viñedo'], params[:tipo]),
      class: "form-check ms-1",
      data: {action: "change->search-variables#updateQuery"}
    %>
    <%= text_field_tag :user_query,
      "",
      class: "form-control ms-1",
      placeholder: "Ingresa zona o palabra clave"
    %>
    <%= text_field_tag :query,
      params[:query],
      class: "form-control ms-1",
      placeholder: "Ingresa zona o palabra clave",
      data: {target: "searchVariables.query"},
      style: 'display: none;'
    %>
    <%= submit_tag "Buscar", class: "btn btn-primary ms-1 boton-busqueda" %>
  <% end %>
</div>


<script>
  document.getElementById("my-form").addEventListener("submit", function(event) {
    event.preventDefault();
    searchcomplete();
    this.submit();
  });

  function searchcomplete() {
    let condicionselect = document.getElementById('condicion').value;
    let tiposelect = document.getElementById('tipo').value;
    let buscador = document.getElementById('user_query').value;
    let busquedacompleta = `${condicionselect} ${tiposelect} ${buscador}`;
    console.log(busquedacompleta);
    let buscadoroculto = document.getElementById('query');
    buscadoroculto.value = busquedacompleta;
  }
</script>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>